---
- hosts: localhost
  connection: localhost
  tasks:
    - name: install Unzip
      apt:
        name: unzip 
        state: present
        updatedcache: true
      become: true
    - name: ensure php7.2 is installed
      apt:
        name: php7.2
        state: present
        update_cache: true
       become: true
