---
- hosts: localhost
  connection: localhost
  tasks:
    - name: install Unzip
      apt:
        name: unzip 
        state: present
    - name: ensure php7.2 is installed
      apt:
        name: php7.2
        state: present
