---
- hosts: localhost
  connection: localhost
  tasks:
    - name: Update apt cache and make sure Vim, Curl and Unzip are installed
      apt:
        update_cache: yes
      loop:
        - curl
        - unzip
